version: '3.9'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
  
  adminer:
    image: 'adminer:latest'
    restart: always
    ports:
      - '8080:8080'

  nats:
    image: 'nats:latest'
    restart: always
    ports:
      - '4222:4222'
  
  redis:
    image: 'redis/redis-stack:latest'
    restart: always
    ports:
      - '6379:6379'
  
volumes:
  dbdata: 