INSERT INTO "book" ("id", "author", "category", "cover", "name", "price", "rating") VALUES
(4,	'John Foreman',	'data_science',	'',	'Data Smart',	299.99,	4.7),
(3,	'Jaideva Goswami',	'signal_processing',	'',	'Fundamentals of Wavelets',	199.99,	0),
(5,	'Goswami, Jaideva',	'signal_processing',	'',	'Fundamentals of Wavelets',	228,	4.5),
(6,	'Foreman, John',	'data_science',	'',	'Data Smart',	235,	4.5),
(7,	'Hawking, Stephen',	'mathematics',	'',	'God Created the Integers',	197,	4.7),
(8,	'Dubner, Stephen',	'economics',	'',	'Superfreakonomics',	179,	4.2),
(9,	'Said, Edward',	'history',	'',	'Orientalism',	197,	4.7),
(10,	'Vapnik, Vladimir',	'data_science',	'',	'Nature of Statistical Learning Theory, The',	230,	4.9),
(11,	'Menon, V P',	'history',	'',	'Integration of the Indian States',	217,	4),
(12,	'Mlodinow, Leonard',	'science',	'',	'Drunkard''s Walk, The',	197,	4.7),
(13,	'Shih, Frank',	'signal_processing',	'',	'Image Processing & Mathematical Morphology',	241,	4.1),
(14,	'Konnikova, Maria',	'psychology',	'',	'How to Think Like Sherlock Holmes',	240,	4.7),
(15,	'Sebastian Gutierrez',	'data_science',	'',	'Data Scientists at Work',	230,	4.2),
(16,	'Vonnegut, Kurt',	'fiction',	'',	'Slaughterhouse Five',	198,	4.4),
(17,	'Villani, Cedric',	'mathematics',	'',	'Birth of a Theorem',	234,	4.2),
(18,	'Sussman, Gerald',	'computer_science',	'',	'Structure & Interpretation of Computer Programs',	240,	4.8),
(19,	'Eraly, Abraham',	'history',	'',	'Age of Wrath, The',	238,	4.7),
(20,	'Kafka, Frank',	'fiction',	'',	'Trial, The',	198,	4.4),
(21,	'Pratt, John',	'data_science',	'',	'Statistical Decision Theory''',	236,	4.8),
(22,	'Nisbet, Robert',	'data_science',	'',	'Data Mining Handbook',	242,	4.2),
(23,	'Wells, H. G.',	'fiction',	'',	'New Machiavelli, The',	180,	4.7),
(24,	'Heisenberg, Werner',	'science',	'',	'Physics & Philosophy',	197,	4.7),
(25,	'Oram, Andy',	'computer_science',	'',	'Making Software',	232,	3.9),
(26,	'Tao, Terence',	'mathematics',	'',	'Analysis, Vol I',	248,	4),
(27,	'Conway, Drew',	'data_science',	'',	'Machine Learning for Hackers',	233,	3.9),
(28,	'Silver, Nate',	'data_science',	'',	'Signal and the Noise, The',	233,	4.7),
(29,	'McKinney, Wes',	'data_science',	'',	'Python for Data Analysis',	233,	3.9),
(30,	'Cormen, Thomas',	'computer_science',	'',	'Introduction to Algorithms',	234,	4.8),
(31,	'Deb, Siddhartha',	'nonfiction',	'',	'Beautiful and the Damned, The',	198,	4.7),
(32,	'Camus, Albert',	'fiction',	'',	'Outsider, The',	198,	4.7),
(33,	'Doyle, Arthur Conan',	'fiction',	'',	'Complete Sherlock Holmes, The - Vol I',	176,	4.4);
